name: dart_web3_multicall
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: '>=2.17.7 <3.0.0'

dependencies:
  http: ^0.13.5
  web3dart: ^2.1.1

dev_dependencies:
  build_runner: ^2.2.0
  lints: ^2.0.0
  test: ^1.16.0
